# Projeto do curso
# Alunos:
# - Cesar Augusto Cardoso
# - Gabryel Marcal

services:
  consul:
    image: hashicorp/consul:latest
    container_name: "consul"
    ports:
      - "5001:8500"

  notificacoesapi:
    image: brunoosilva/ms-notificacoesservice
    # build:
    #   context: .
    #   dockerfile: NotificacoesAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIROMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Consul__Discovery__Hostname=notificacoesapi
    ports:
      - "4001:8080"

  pedidosapi:
    image: cesaraugusto0/pedidosapi
    build:
      context: .
      dockerfile: Pedido.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIROMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "4002:8080"

  pizzaapi:
    image: cesaraugusto0/pizzaapi
    build:
      context: .
      dockerfile: Pizza.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIROMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "4003:8080"

  gatewayapi:
    image: cesaraugusto0/gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIROMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "3001:8080"

  fake-smtp-server:
    image: gessnerfl/fake-smtp-server:latest
    container_name: "fake-smtp-server"
    restart: always
    ports:
      # - 8025:8025      #expose smtp port
      - 7001:8080      #expose web ui
      - 7002:8081      #expose management api

